_format_version: "2.1"
_transform: true

services:
  - name: auth-v1
    url: http://auth:9999
    routes:
      - name: auth-v1-route
        strip_path: true
        paths:
          - /auth/v1

  - name: rest-v1
    url: http://rest:3000
    routes:
      - name: rest-v1-route
        strip_path: true
        paths:
          - /rest/v1

consumers:
  - username: anon
    keyauth_credentials:
      - key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlzcyI6InN1cGFiYXNlIiwiaWF0IjoxNzczNDk1Njg4LCJleHAiOjIwODg4NTU2ODh9.nWh9Jb8I1gWrExGYCOPvoqAtiFxr3Yy-96By1U3Ri_U

  - username: service_role
    keyauth_credentials:
      - key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic2VydmljZV9yb2xlIiwiaXNzIjoic3VwYWJhc2UiLCJpYXQiOjE3NzM0OTU2ODgsImV4cCI6MjA4ODg1NTY4OH0.E1p2xwTZbcQKdcaG1U97xPrsWd_gGa52z8jdb7pghZE

plugins:
  - name: cors
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      headers:
        - apikey
        - authorization
        - content-type
        - accept
        - prefer
        - accept-profile
        - content-profile
        - x-client-info
        - x-supabase-api-version
      exposed_headers:
        - content-range
        - x-total-count
      credentials: true
      max_age: 3600

  - name: key-auth
    config:
      key_names:
        - apikey
      hide_credentials: false
